"""
France country configuration
"""

FRANCE_CONFIG = {
    "name": "France",
    "language": "fr",
    "wikipedia_api": "https://fr.wikipedia.org/w/api.php",
    "wikipedia_base": "https://fr.wikipedia.org/wiki/",

    # Labels in local language
    "labels": {
        "municipality": "Commune",
        "total_hab": "TOTAL HAB",
        "hab_urban": "Nº HAB URBAIN",
        "hab_rural": "Nº HAB RURAL",
        "equipos_urban": "ÉQUIPES URBAIN",
        "equipos_rural": "ÉQUIPES RURAL",
        "total_equipos": "TOTAL ÉQUIPES",
        "rural": "Zone Rurale",
        "urban": "Zone Urbaine",
    },

    # French departments (simplified list - major departments)
    "regions": [
        "Ain", "Aisne", "Allier", "Alpes-de-Haute-Provence", "Hautes-Alpes",
        "Alpes-Maritimes", "Ardèche", "Ardennes", "Ariège", "Aube",
        "Aude", "Aveyron", "Bouches-du-Rhône", "Calvados", "Cantal",
        "Charente", "Charente-Maritime", "Cher", "Corrèze", "Corse-du-Sud",
        "Haute-Corse", "Côte-d'Or", "Côtes-d'Armor", "Creuse", "Dordogne",
        "Doubs", "Drôme", "Eure", "Eure-et-Loir", "Finistère",
        "Gard", "Haute-Garonne", "Gers", "Gironde", "Hérault",
        "Ille-et-Vilaine", "Indre", "Indre-et-Loire", "Isère", "Jura",
        "Landes", "Loir-et-Cher", "Loire", "Haute-Loire", "Loire-Atlantique",
        "Loiret", "Lot", "Lot-et-Garonne", "Lozère", "Maine-et-Loire",
        "Manche", "Marne", "Haute-Marne", "Mayenne", "Meurthe-et-Moselle",
        "Meuse", "Morbihan", "Moselle", "Nièvre", "Nord",
        "Oise", "Orne", "Pas-de-Calais", "Puy-de-Dôme", "Pyrénées-Atlantiques",
        "Hautes-Pyrénées", "Pyrénées-Orientales", "Bas-Rhin", "Haut-Rhin", "Rhône",
        "Haute-Saône", "Saône-et-Loire", "Sarthe", "Savoie", "Haute-Savoie",
        "Paris", "Seine-Maritime", "Seine-et-Marne", "Yvelines", "Deux-Sèvres",
        "Somme", "Tarn", "Tarn-et-Garonne", "Var", "Vaucluse",
        "Vendée", "Vienne", "Haute-Vienne", "Vosges", "Yonne",
        "Territoire de Belfort", "Essonne", "Hauts-de-Seine", "Seine-Saint-Denis",
        "Val-de-Marne", "Val-d'Oise"
    ],

    # Page title pattern for French Wikipedia
    "page_title_pattern": "Liste_des_communes_{region}",
    "default_region_pattern": "de_{region}",

    # Region mappings - French requires articles (l', la, le, du, des, de la, etc.)
    "region_page_mappings": {
        # l' + vowel
        "Ain": "de_l'Ain",
        "Aisne": "de_l'Aisne",
        "Allier": "de_l'Allier",
        "Ardèche": "de_l'Ardèche",
        "Ariège": "de_l'Ariège",
        "Aube": "de_l'Aube",
        "Aude": "de_l'Aude",
        "Aveyron": "de_l'Aveyron",
        "Essonne": "de_l'Essonne",
        "Eure": "de_l'Eure",
        "Eure-et-Loir": "d'Eure-et-Loir",
        "Hérault": "de_l'Hérault",
        "Ille-et-Vilaine": "d'Ille-et-Vilaine",
        "Indre": "de_l'Indre",
        "Indre-et-Loire": "d'Indre-et-Loire",
        "Isère": "de_l'Isère",
        "Oise": "de_l'Oise",
        "Orne": "de_l'Orne",
        "Yonne": "de_l'Yonne",
        # du + masculine
        "Bas-Rhin": "du_Bas-Rhin",
        "Calvados": "du_Calvados",
        "Cantal": "du_Cantal",
        "Cher": "du_Cher",
        "Doubs": "du_Doubs",
        "Finistère": "du_Finistère",
        "Gard": "du_Gard",
        "Gers": "du_Gers",
        "Haut-Rhin": "du_Haut-Rhin",
        "Jura": "du_Jura",
        "Loiret": "du_Loiret",
        "Lot": "du_Lot",
        "Lot-et-Garonne": "de_Lot-et-Garonne",
        "Morbihan": "du_Morbihan",
        "Nord": "du_Nord",
        "Pas-de-Calais": "du_Pas-de-Calais",
        "Puy-de-Dôme": "du_Puy-de-Dôme",
        "Rhône": "du_Rhône",
        "Tarn": "du_Tarn",
        "Tarn-et-Garonne": "de_Tarn-et-Garonne",
        "Var": "du_Var",
        "Vaucluse": "de_Vaucluse",
        "Territoire de Belfort": "du_Territoire_de_Belfort",
        # de la + feminine
        "Charente": "de_la_Charente",
        "Charente-Maritime": "de_la_Charente-Maritime",
        "Corrèze": "de_la_Corrèze",
        "Corse-du-Sud": "de_la_Corse-du-Sud",
        "Côte-d'Or": "de_la_Côte-d'Or",
        "Creuse": "de_la_Creuse",
        "Dordogne": "de_la_Dordogne",
        "Drôme": "de_la_Drôme",
        "Gironde": "de_la_Gironde",
        "Haute-Corse": "de_la_Haute-Corse",
        "Haute-Garonne": "de_la_Haute-Garonne",
        "Haute-Loire": "de_la_Haute-Loire",
        "Haute-Marne": "de_la_Haute-Marne",
        "Haute-Saône": "de_la_Haute-Saône",
        "Haute-Savoie": "de_la_Haute-Savoie",
        "Haute-Vienne": "de_la_Haute-Vienne",
        "Loire": "de_la_Loire",
        "Loire-Atlantique": "de_la_Loire-Atlantique",
        "Lozère": "de_la_Lozère",
        "Manche": "de_la_Manche",
        "Marne": "de_la_Marne",
        "Mayenne": "de_la_Mayenne",
        "Meuse": "de_la_Meuse",
        "Moselle": "de_la_Moselle",
        "Nièvre": "de_la_Nièvre",
        "Sarthe": "de_la_Sarthe",
        "Savoie": "de_la_Savoie",
        "Seine-Maritime": "de_la_Seine-Maritime",
        "Seine-et-Marne": "de_Seine-et-Marne",
        "Somme": "de_la_Somme",
        "Vendée": "de_la_Vendée",
        "Vienne": "de_la_Vienne",
        # des + plural
        "Alpes-de-Haute-Provence": "des_Alpes-de-Haute-Provence",
        "Alpes-Maritimes": "des_Alpes-Maritimes",
        "Ardennes": "des_Ardennes",
        "Bouches-du-Rhône": "des_Bouches-du-Rhône",
        "Côtes-d'Armor": "des_Côtes-d'Armor",
        "Deux-Sèvres": "des_Deux-Sèvres",
        "Hautes-Alpes": "des_Hautes-Alpes",
        "Hautes-Pyrénées": "des_Hautes-Pyrénées",
        "Hauts-de-Seine": "des_Hauts-de-Seine",
        "Landes": "des_Landes",
        "Pyrénées-Atlantiques": "des_Pyrénées-Atlantiques",
        "Pyrénées-Orientales": "des_Pyrénées-Orientales",
        "Vosges": "des_Vosges",
        "Yvelines": "des_Yvelines",
        # Special cases
        "Loir-et-Cher": "de_Loir-et-Cher",
        "Maine-et-Loire": "de_Maine-et-Loire",
        "Meurthe-et-Moselle": "de_Meurthe-et-Moselle",
        "Paris": "de_Paris",
        "Saône-et-Loire": "de_Saône-et-Loire",
        "Seine-Saint-Denis": "de_la_Seine-Saint-Denis",
        "Val-de-Marne": "du_Val-de-Marne",
        "Val-d'Oise": "du_Val-d'Oise",
    },
}
